### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by kallmetony** [IAFEnvoy/Uranus#1]
I am from [this issue](https://github.com/IAFEnvoy/IceAndFire-Fabric/issues/60)

Crash report: https://mclo.gs/EnNN0Si

I noticed that game crashes because of `at knot//com.iafenvoy.uranus.util.RandomHelper.randomOne(RandomHelper.java:30)`

Will you fix this bug or should I try and do this by myself?

**Comment by IAFEnvoy** [comment]
I need time to test it out since this is an impossible crash

**Comment by IAFEnvoy** [comment]
bug investigated and it is a bug in iaf, fixed and will be published later

**Comment by kallmetony** [comment]
I would like to thank you. Your mod is awesome!
